### ISSUE TITLE
Update: native-windows-gui crate is not maintained any more.

### ISSUE THREAD

**Issue by crlf0710** [not-yet-awesome-rust/not-yet-awesome-rust#44]
According to its readme.md in the repo.

**Comment by ErichDonGubler** [comment]
Confirmed! Ah, man...I've fixed this in https://github.com/not-yet-awesome-rust/not-yet-awesome-rust/commit/fd9bd09017b8a283bc0cbcfbe15cd9198e1b6d6f. Thanks for the report!
