### ISSUE TITLE
SSH client library

### ISSUE THREAD

**Issue by sanxiyn** [not-yet-awesome-rust/not-yet-awesome-rust#47]
As I understand, [Thrussh](https://crates.io/crates/thrussh) is a full implementation of SSH, both client and server. It is fully in Rust except for cryptographic primitives.

**Comment by ErichDonGubler** [comment]
@sanxiyn: Just wanted to ping you here to get your feedback if possible. :)

**Comment by ErichDonGubler** [comment]
@sanxiyn: Unless I get feedback soon, I'm going to have to close this issue -- it's hard to act on this without further information!
