### ISSUE TITLE
General Compression Library?

### ISSUE THREAD

**Issue by nugend** [not-yet-awesome-rust/not-yet-awesome-rust#51]
Is there a library which handles the varying compression formats automatically? As in, pass a `std::io::Read` in and it produces a `Result<Decompressed,CompressedIOError>` or whatever?

**Comment by ErichDonGubler** [comment]
So, to make it clear, I think you're talking about two distinct requirements:

* A library with a unified `Result` type after decompressing data
* A library that auto-detects what compression was used on the data stream passed in via an implementation of `Read`.

Sound right so far?

**Comment by ErichDonGubler** [comment]
Assuming "yes" to my requirements questions above:

* The [`anycat` binary](https://github.com/xgillard/anycat/) multiplexes file archives to the right decompression logic based on file extension (source [here](https://github.com/xgillard/anycat/blob/master/src/lib.rs), but that doesn't fit only using an instance of `Read`.
* The [`compression` lib](https://docs.rs/compression/0.1.1/compression/) aggregates libraries for varying compression formats into a single `prelude`, but there doesn't seem to be anything that adapts the interfaces to be consistent between the libs themselves.

At first glance, it looks like there's nothing in the ecosystem that immediately fulfills your needs here, but most of the heavy lifting has been done for you!

**Comment by nugend** [comment]
@ErichDonGubler Yes and yes. I'll look into those. Seems like it'd be fairly easy to make something!

**Comment by ErichDonGubler** [comment]
@nugend: Awesome. Does the info I gave you take care of your issue? :)
