### ISSUE TITLE
SSH seems to be implemented

### ISSUE THREAD

**Issue by Shnatsel** [not-yet-awesome-rust/not-yet-awesome-rust#52]
SSH client library now exists. https://crates.io/crates/thrussh

Description and philosophy: https://pijul.org/thrussh/

Latest status update for Thrussh: https://pijul.org/2017/12/06/thrussh-0.17/

**Comment by ErichDonGubler** [comment]
@sanxiyn: Has indicated twice now that ThruSSH is missing some features, but until now I haven't heard what those are. I've just authored an edit removing the entry entirely -- it was added without any real information, which at this point I would consider poor content for this repo.

Thanks for taking the time to file an issue! :)
