### ISSUE TITLE
AMQP 1.0

### ISSUE THREAD

**Issue by nugend** [not-yet-awesome-rust/not-yet-awesome-rust#58]
Have been futzing with AMQP at work. Noticed that there's a few 0.9.1 libraries for Rust, but none for the 1.0 version.

My understanding is that the protocols are significantly different.

**Comment by ErichDonGubler** [comment]
@nugend: This sounds interesting to add -- could you make a quick edit PR and add this in? :)

**Comment by nugend** [comment]
Sorry, which section would that go under?

**Comment by ErichDonGubler** [comment]
Hmm...maybe it deserves to stand in its own (new) "Networking and Protocols" section?
