### ISSUE TITLE
Streamlining running examples

### ISSUE THREAD

**Issue by lgarczyn** [not-yet-awesome-rust/not-yet-awesome-rust#66]
A large part of my workflow is to clone a library (say rust-sdl2) in a /tmp/ folder, open a new tab in that folder, and call `cargo --example` on one of the listed examples, then go back to what I was doing.

A cargo plugin (and maybe a feature later on) allowing to run `cargo example rust-sdl2  example-n1` that would just work, without having to create a whole folder ourselves, and maybe even caching large libraries, would be a godsend.

If it is made part of cargo itself, trying out a crate becomes even faster. Anyone can just write in their repo: call `cargo example mylib example-n1` and be over with it.

Some sandboxing might even be added for more safety.

**Comment by ErichDonGubler** [comment]
Hmmm, this sounds like a shoe-in for a Cargo subcommand...and this suggestion might be a better fit for [Request for Implementation](https://github.com/dtolnay/request-for-implementation), where several interesting subcommand requests already exist! I don't see a ton of design/ecosystem work here to do, which is the direction I think NYAR should go. 

So, in summary, I don't think I'll be putting this here, but I'd be absolutely happy to file this in RfI if you want!

**Comment by lgarczyn** [comment]
That's a great idea, I don't really think I have the knowledge to write the RFI myself.

**Comment by lgarczyn** [comment]
I ended up creating the [RFI](https://github.com/dtolnay/request-for-implementation/issues/30), thanks for the suggestion.

**Comment by ErichDonGubler** [comment]
@lgarczyn: Wonderful! Is there anything else I can do for you here, or should this just be closed?
