### ISSUE TITLE
JsonSchema

### ISSUE THREAD

**Issue by jonathan-s** [not-yet-awesome-rust/not-yet-awesome-rust#69]
Does not currently exist for rust - it might be useful.

**Comment by AlbanMinassian** [comment]
maybe https://github.com/rustless/valico

**Comment by jonathan-s** [comment]
True that, closing this then.

**Comment by ErichDonGubler** [comment]
Yes, [`valico`](https://github.com/rustless/valico) is actually something I've maintained in the past and should work for most needs that I'm aware of (which I'm not an expert in, mind you!). Thanks for taking the time to make an issue! I hope you come back soon if and when you find other things you have other things that you're not sure are awesome in Rust yet. :)
