### ISSUE TITLE
QR decoder implemented

### ISSUE THREAD

**Issue by WanzenBug** [not-yet-awesome-rust/not-yet-awesome-rust#74]
I ported the C library linked in #17 and used by the [quirc crate](https://crates.io/crates/quirc) to rust. Link [here](https://github.com/WanzenBug/rqrr)

Its not a 1:1 port as the interface is quite C-ism heavy so I set about cleaning it up a bit. Its still not finished but from my limited tests it works well enough.

Would be happy to receive some feedback 😄

**Comment by ErichDonGubler** [comment]
Wooot! You da man! I'll get to updating the list shortly.

**Comment by ErichDonGubler** [comment]
PR is up -- let me know on that thread if you have any objections. I'll close it tomorrow if I don't hear anything. :)

**Comment by piderman314** [comment]
Haha pretty cool that we announced within a few hours of each other ;)
