### ISSUE TITLE
BinHex 4 (.hqx) decoder that checks CRCs when decoding

### ISSUE THREAD

**Issue by ssokolow** [not-yet-awesome-rust/not-yet-awesome-rust#91]
Currently, there appears to be no [BinHex 4](https://en.wikipedia.org/wiki/BinHex#BinHex_4_(.hqx)) decoder crate available.

This is a problem for me because I want to rewrite my batch file-corruption detection tool in Rust before releasing it and I'm relying on the [`binhex` module](https://docs.python.org/3/library/binhex.html) from the Python standard library because the other `apt`-installable binhex decoders I could invoke as subprocesses are unsuitable.

(`uudeview` says right in its manpage that it ignores BinHex CRCs. I can't remember what's wrong with `hexbin`, but I know I checked it and found it wanting.)

**UPDATE:** Here's the [BinHex 4.0 spec](http://files.stairways.com/other/binhex-40-specs-info.txt).

**Comment by nramos0** [comment]
I have recently published a crate for this: https://github.com/nramos0/binhex4-rs, `binhex4` on crates.io. Anyone that sees this in the future please feel free to take a look and see if it fits your needs, issues / pull requests are welcome

**Comment by ssokolow** [comment]
I'll see if I can find time to give it a try within the next few days. (Maybe even set up a harness to differentially fuzz it against Python's standard library implementation)

I notice that crates.io lists the size as  2.83 MB, which suggests that you probably need to set some exclusions for the packaging process, given that I'd expect something like this to be in the tens of kilobytes at most.

**Comment by nramos0** [comment]
Oh, thank you for pointing that out. My guess is it is including some test hqx files from the repo in the package. I'll take care of it

**Comment by ssokolow** [comment]
Sorry for going quiet. I got carried away working on porting the "minimally annoying to users" anti-spam code some of my sites use from PHP and Python to Rust.

I'm taking a look at `binhex4`'s API and I already see something that's less than optimal. The current API design requires `size_of_raw_binhex_text + size_of_decoded_data` RAM to operate.

Would you be willing to change the `hexbin` function to operate in a streaming manner? (i.e. Take anything that implements the `Read` trait as input and implement `Read` similar to something like `BufReader` or [`flate2::read::GzDecoder`](https://docs.rs/flate2/latest/flate2/read/struct.GzDecoder.html))

If not, I'd be willing to take a crack at it... just not right now because the project where I need a BinHex4 decoder is on hold while I work on more pressing ones.

Either way, I'll try to set up some differential fuzzing against the Python standard library BinHex4 decoder today or tomorrow.

**Comment by ErichDonGubler** [comment]
@ssokolow, @nramos0: Is it fair to say that the issue (a total lack of BinHex4 decoders in the Rust ecosystem) is closable for now, then?

**Comment by ssokolow** [comment]
Good point. Yeah.
